DROP table IF EXISTS employee;
DROP TABLE IF EXISTS TEMPORAL;
DROP TABLE IF EXISTS CATALOG;
drop table IF EXISTS BOOK_I18N;
drop table IF EXISTS BOOK;
drop table IF EXISTS AUTHOR;
DROP TABLE IF EXISTS TC;
DROP TABLE IF EXISTS TB;
DROP TABLE IF EXISTS TA;
drop table IF EXISTS GALLERY_PAINTING;
drop table IF EXISTS GALLERY;
drop table IF EXISTS PAINTING;
DROP TABLE IF EXISTS ARTIST;
drop table IF EXISTS IMAGE;

DROP FUNCTION IF EXISTS hiFive;

CREATE TABLE `ARTIST`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`VERSION`INTEGER NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
	`GENDER` VARCHAR(1) NOT NULL,
	`BIRTHDAY` DATETIME,
	`CREATION` TIMESTAMP NULL DEFAULT NULL,
	`MODIFICATION` TIMESTAMP NULL DEFAULT NULL
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `PAINTING`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`VERSION`INTEGER NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `PRICE` DECIMAL(20, 2),
    `ARTIST_ID` BIGINT,
    `IMAGE_ID` BIGINT
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `IMAGE`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`VERSION` INTEGER NOT NULL,
    `CONTENT` LONGBLOB
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `GALLERY`(
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`VERSION` BIGINT NOT NULL,
	`NAME` VARCHAR(255) NOT NULL,
	`ADDRESS` VARCHAR(255)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `GALLERY_PAINTING` (
	`GALLERY` BIGINT NOT NULL,
	`PAINTING` BIGINT NOT NULL
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

ALTER TABLE `GALLERY_PAINTING` ADD CONSTRAINT `GALERY_PAINTING_PK` PRIMARY KEY (`GALLERY`,`PAINTING`);
ALTER TABLE `GALLERY_PAINTING` ADD CONSTRAINT `GALERY_PAINTING_FK1` FOREIGN KEY (`GALLERY`) REFERENCES `GALLERY`(`ID`);
ALTER TABLE `GALLERY_PAINTING` ADD CONSTRAINT `GALERY_PAINTING_FK2` FOREIGN KEY (`PAINTING`) REFERENCES `PAINTING`(`ID`);

ALTER TABLE `PAINTING` ADD CONSTRAINT `PAINTING_FK1` FOREIGN KEY(`ARTIST_ID`) REFERENCES `ARTIST`(`ID`);
ALTER TABLE `PAINTING` ADD CONSTRAINT `PAINTING_FK2` FOREIGN KEY(`IMAGE_ID`) REFERENCES `IMAGE`(`ID`);

-- i18n
CREATE TABLE `AUTHOR`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`VERSION`INTEGER NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
	`BIRTHDAY` DATE
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `BOOK`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`VERSION`INTEGER NOT NULL,
	`PRICE` DECIMAL,
    `AUTHOR_ID` BIGINT
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

ALTER TABLE `BOOK` ADD CONSTRAINT `FK1_BOOK` FOREIGN KEY(`AUTHOR_ID`) REFERENCES `AUTHOR`(`ID`);

CREATE TABLE `BOOK_I18N`(
    `ID` BIGINT NOT NULL,
	`LANG` VARCHAR(10) NOT NULL,
    `NAME` VARCHAR(255) NOT NULL
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

ALTER TABLE `BOOK_I18N` ADD PRIMARY KEY (`ID`, `LANG`);
ALTER TABLE `BOOK_I18N` ADD CONSTRAINT `FK1_BOOK_I18N` FOREIGN KEY(`ID`) REFERENCES `BOOK`(`ID`);

--

CREATE TABLE `TA` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`TIPO` VARCHAR(255)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `TB` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`DSC` VARCHAR(255),
	`FK` BIGINT
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

CREATE TABLE `TC` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`DSC` VARCHAR(255),
	`FK` BIGINT
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

--

CREATE TABLE `CATALOG` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	`KIND` VARCHAR(30),
	`TOKEN` VARCHAR(30),
	`VALUE` VARCHAR(255)
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

----
-- performance tests
----

CREATE TABLE `EMPLOYEE` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
    `NAME` VARCHAR(100) NOT NULL,
	`SEX` BOOL,
    `PAY_GRADE` INTEGER,
    `EYE_COLOR` VARCHAR(1000),
	`CREATION` TIMESTAMP NULL DEFAULT NULL
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

----
-- Temporal tests
----

CREATE TABLE `TEMPORAL` (
	`ID` BIGINT NOT NULL,
	PRIMARY KEY(ID),
    `CLOCK` TIME NULL,
	`CALENDAR` DATE NULL,
	`NOW` DATETIME NULL,
	`INSTANT` TIMESTAMP NULL DEFAULT NULL
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8;

DROP FUNCTION IF EXISTS `hiFive`;

CREATE FUNCTION hiFive() RETURNS INTEGER DETERMINISTIC
   RETURN 5;
