drop table IF EXISTS GALLERY_PAINTING;
drop table IF EXISTS PAINTING;
DROP TABLE IF EXISTS ARTIST;
drop table IF EXISTS IMAGE;
drop table IF EXISTS GALLERY;

CREATE TABLE ARTIST(
    ID INT IDENTITY,
	VERSION INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
	GENDER VARCHAR(1) NOT NULL,
	BIRTHDAY TIMESTAMP,
	CREATION TIMESTAMP,
	MODIFICATION TIMESTAMP
);

CREATE TABLE PAINTING(
    ID INT IDENTITY,
	VERSION INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(20, 2),
    ARTIST_ID INT,
    IMAGE_ID INT
);

CREATE TABLE IMAGE(
    ID INT IDENTITY,
	VERSION INT NOT NULL,
    CONTENT BLOB
);

CREATE TABLE GALLERY (
	ID INT IDENTITY,
	VERSION INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	ADDRESS VARCHAR(255)
);

CREATE TABLE GALLERY_PAINTING (
	GALLERY INT NOT NULL,
	PAINTING INT NOT NULL
);

ALTER TABLE GALLERY_PAINTING ADD CONSTRAINT GALERY_PAINTING_PK PRIMARY KEY (GALLERY,PAINTING);
ALTER TABLE GALLERY_PAINTING ADD CONSTRAINT GALERY_PAINTING_FK1 FOREIGN KEY (GALLERY) REFERENCES GALLERY(ID);
ALTER TABLE GALLERY_PAINTING ADD CONSTRAINT GALERY_PAINTING_FK2 FOREIGN KEY (PAINTING) REFERENCES PAINTING(ID);

ALTER TABLE PAINTING ADD CONSTRAINT PAINTING_FK1 FOREIGN KEY(ARTIST_ID) REFERENCES ARTIST(ID);
ALTER TABLE PAINTING ADD CONSTRAINT PAINTING_FK2 FOREIGN KEY(IMAGE_ID) REFERENCES IMAGE(ID);

----------
-- i18n --
----------
CREATE TABLE AUTHOR(
    ID INT IDENTITY,
	VERSION INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
	BIRTHDAY TIMESTAMP
);

CREATE TABLE BOOK(
    ID INT IDENTITY,
	VERSION INT NOT NULL,
	PRICE DECIMAL,
    AUTHOR_ID INT
);

ALTER TABLE BOOK ADD CONSTRAINT FK1_BOOK FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID);

CREATE TABLE BOOK_I18N(
    ID INT NOT NULL,
	LANG VARCHAR(10) NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

ALTER TABLE BOOK_I18N ADD PRIMARY KEY (ID, LANG);
ALTER TABLE BOOK_I18N ADD CONSTRAINT FK1_BOOK_I18N FOREIGN KEY(ID) REFERENCES BOOK(ID);



----
-- performance tests
----

create table employee (
    id INT IDENTITY,
    name varchar(100) not null,
	sex boolean,
    PAY_GRADE INTEGER,
    CREATION timestamp
);

--

CREATE TABLE TA (
	ID BIGINT IDENTITY,
	TIPO VARCHAR(255)
);

CREATE TABLE TB (
	ID BIGINT IDENTITY,
	DSC VARCHAR(255),
	FK INTEGER
);

CREATE TABLE TC (
	ID BIGINT IDENTITY,
	DSC VARCHAR(255),
	FK INTEGER
);

--

CREATE TABLE "CATALOG" (
	ID BIGINT IDENTITY,
	KIND VARCHAR(30),
	TOKEN VARCHAR(30),
	VALUE VARCHAR(255)
);

CREATE TABLE TEMPORAL (
	ID BIGINT IDENTITY,
    CLOCK TIME NULL,
	CALENDAR DATE NULL,
	NOW TIMESTAMP NULL,
	INSTANT TIMESTAMP NULL
);
